name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: 5.0.100
    - name: Build
      run: dotnet build "src/EFCore.Extension.Logger/EFCore.Extension.Logger/EFCore.Extension.Logger.csproj" --configuration Release
    - name: Pack
      run: dotnet pack "src/EFCore.Extension.Logger/EFCore.Extension.Logger/EFCore.Extension.Logger.csproj" --configuration Release -p:PackageVersion=1.0.4 --output nupkgs
    - name: Publish
      run: dotnet nuget push "nupkgs/EFCore.Extension.Logger.1.0.4.nupkg" --skip-duplicate --api-key oy2irsgtchjxgn24iz2aotr6su7hjgse3b6w6zqn5re6qi --source "https://api.nuget.org/v3/index.json"
